python: 3.6
language: python
compiler: gcc
env:
  global:
  - PKG_NAME=bgen_reader
  - CIBW_SKIP="cp27-* cp34-* cp35-*"
  - CIBW_BEFORE_BUILD_LINUX="ci/before-build-linux"
  - CIBW_BEFORE_BUILD_MACOS="ci/before-build-macos"
matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic
      before_install:
        - brew update
        - brew outdated python || brew upgrade python
        - brew unlink python && brew link python
        - export PATH="/usr/local/opt/python/libexec/bin:$PATH"
        - hash -r
        - python -m pip install --upgrade pip setuptools wheel
addons:
  apt:
    packages:
    - libffi-dev
    - libffi6
install:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/zstd.install/master/install)
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/almosthere/master/install)
- bash <(curl -fsSL https://raw.githubusercontent.com/limix/bgen/master/install)
script:
- |
  if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
    sudo mkdir -p /usr/local/man
    sudo chown -R "${USER}:admin" /usr/local/man
  fi
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
- |
  if [ "${TRAVIS_TAG:-}" != "" ]; then
    python -m pip install cibuildwheel>=0.9.1
    cibuildwheel --output-dir wheelhouse
    python -m pip install twine
    python -m twine upload --skip-existing wheelhouse/*
  fi
notifications:
  email:
    recipients:
    - danilo.horta@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: FQibXjKOCq3lzPn9QLTZ0GMZXOkq3A35G8PSLrbFjOtd7BlkX0nJ9kuMg4NMP2OaAVirv3L4Kd8cceWifx1F/LAn1u+ABiVfMrM4xV3rA8xHL8Yr4zyesEPsDXoZBAymJPBd3RMeib3sCjtPQl2o9reUeycTyTAwDC010PnR29rTH6WLutpS8WcjKMxkfh2+h6Ks85o6DWLu+sVRnrxZq/y+xdbwHzZiSUwjGA8rF88Iw/EBfFNDR9DDiQyYY+dmvi7efoYPol07ZRVAmKdxK9TXPlye/x+M0mu9jeMyxhdUQc1x4YhK5CXJEI3R1bo8yEpKCskCOVpYOxkbOeDM1cu3rptROhbzQs+02j4Moqk5vC+4Gl6NwuB2fbnzijWpq17Kg5oQppMBMP8f7y85ws75owMFdYGdw49tR2pyL8BYsIqxBFq/SYhYwuZ7wnGNgKN4DKxwc+lRv/zICAipt04tMQsyPXq071wjZt44gZgoJ3rYbfbYNShDQOI+nbKhwHRV5/PmkBDT/KD3KVapjmT1q2wY7gGN8/2dIrPjmqveBgKho3QAmc0UV8SBVLw4rZxGJRGzRR6y58sCd0ynzB0tggUksrGO/gT1QnzgABPQ2Of137HfDEXXaSKdc4HCw9W0D0gltLaHV5b8iU4gQf1VsAt/I9mmp5Thrtvf9cc=
  on:
    tags: true
    repo: limix/bgen-reader-py
    branch: master
    python: 3.6
